### ISSUE TITLE
Old tiles used after redrawTiles() is used

### ISSUE THREAD

**Issue by Nohus** [peterLaurence/MapCompose#27] opened 2021-12-05 13:35 UTC
There is a bug reproduction demo [on this branch](https://github.com/Nohus/MapCompose/tree/bug_reproduction).

The demo switches the `TileStreamProvider` implementation and then calls `redrawTiles()`. As the tiles are loading, it does so again. This results in the wrong tiles being displayed. I think this may be the cause for #26 too, although I am not sure.

https://user-images.githubusercontent.com/11064768/144748637-9f1120ef-04c9-45b9-bfb0-b77f326a2e8e.mp4

The number of incorrect tiles is equal to `workerCount`.

**Comment by peterLaurence** [comment] 2021-12-05 13:50
Well done for reproducing it. Right now I'm polishing some layers APIs and will have look at this after.
Is this issue affecting `master`, `layers`, or both?

**Comment by Nohus** [comment] 2021-12-05 13:52
Both.

**Comment by peterLaurence** [comment] 2021-12-05 13:58
Note for self: the internal state of the collecter should be cleared, or a new collector should be created.

**Comment by peterLaurence** [comment] 2021-12-05 16:14
This is because you are changing your `TileStreamProvider`, while it's concurrently accessed by worker threads. There's no synchronization on the `TileStreamProvider` (and there shouldn't). So nothing prevents you from altering it while the tile collector is still alive.
No matter how well the tile collector is restarted (re-created or not), the `TileStreamProvider` is still concurrently accessed. 
One way to circumvent this issue is to re-create the MapState (yes, I know, this isn't what you want to do. But that illustrates the concurrency issue). See below. Also note, the example I give you at the end only works if you change L.101 of `TileCollector` to:
```
val i = kotlin.runCatching {
     tileStreamProvider.getTileStream(spec.row, spec.col, spec.zoom)
}.getOrNull()
```

My last thought is this `redrawTiles` API was a bad idea. For the moment, I'm considering deprecating it and favor the new API
available in `layers` branch : `setPrimaryLayer`. The idea is that a `TileStreamProvider` should be immutable, and we should be able to dynamically change of primary layer. Redrawing tiles would become an internal operation.
FYI, I haven't fully tested `setPrimaryLayer` yet.

This illustrates that there were a concurrent - and improper - access to `type`:
```
class SimpleDemoVM(application: Application) : AndroidViewModel(application) {
    private val appContext: Context by lazy {
        getApplication<Application>().applicationContext
    }
    private var type = 0  // was accessed by several threads in original example - should have been annotated @Volatile 
                                    // (but wouldn't have fixed the issue)
    var state: MapState by mutableStateOf(makeMapState(type))

    init {
        viewModelScope.launch {
            while (true) {
                changeMapType()
                delay(200)
                changeMapType()
                delay(2000)
            }
        }
    }

    private fun makeMapState(type: Int): MapState {
        return MapState(
            levelCount = 1,
            fullWidth = 4352,
            fullHeight = 4096,
            workerCount = 8,
            tileStreamProvider = { row, col, zoom ->
                runBlocking {
                    getTile(col, row, type)
                }
            }
        )
    }

    private fun changeMapType() {
        state.shutdown()
        type = ((0..2) - type).random()
        state = makeMapState(type)
    }

    private suspend fun getTile(x: Int, y: Int, type: Int): InputStream? {
        delay((80L..200L).random())
        return appContext.assets?.open("tiles/test/tile_${type}_${x}_${y}.png")
    }
}
```

**Comment by Nohus** [comment] 2021-12-05 16:20
That's fair, so what is the proper way of changing the `TileStreamProvider` on `master`?

**Comment by peterLaurence** [comment] 2021-12-05 16:22
Not sure at the moment. Yeah, probably wait until `layers` is merged.

**Comment by peterLaurence** [comment] 2021-12-06 08:29
I've added a new demo called "Test primary layer switch". Look how a fresh new instance of `TileStreamProvider` is created each time, and never mutated.
If you used the same technique in your app (mutate your instance of `TileStreamProvider`, and invoke `redrawTiles()`, then if anything good came out of it, it's by happy accident. This includes the fix made in master. The problem is still there, and might show up again (under different circumstances, on another device, etc).

I like stress test like this one. Maybe we should make a "test" app, in addition to the existing demo. For instance, `TestPrimaryLayerSwitch` is in the demo, but it's temporary. What do you think?

**Comment by Nohus** [comment] 2021-12-06 10:33
In your demo the bug still happens, although now it's only once every 15-20 refreshes, not repeatable every time like it was.

![image](https://user-images.githubusercontent.com/11064768/144830546-a126377c-9654-4a83-8dc3-eed32d8260b9.png)

See the new `bug_reproduction` branch, I re-added the tile loading delay so the bug has a chance to happen.

**Comment by peterLaurence** [comment] 2021-12-06 11:24
Although the visual effet looks the same, the underlying issue is this time completely different. No cancellable calls don't play nice with coroutine cancellation. Nice catch though.
I made a change which reduces the likelihood of this particular issue. I've replaced the `runBlocking` by a Thread.sleep, which is more representative of a real blocking call. Using `runBlocking` here is a bad practice and we shouldn't expect it there. 
However, the problem is still there.
I believe that the proper fix is to have `suspend` and cancellelable `TileStreamProvider`. But I might find a better solution.

**Comment by peterLaurence** [comment] 2021-12-06 11:54
I've pushed another change which seems to fix the issue, for now.

**Comment by peterLaurence** [comment] 2021-12-06 12:44
The last strategy I've implemented (filtering using the last unique main layer id), seems to be more robust.

**Comment by Nohus** [comment] 2021-12-06 13:02
> Check active state in tile collector

![image](https://user-images.githubusercontent.com/11064768/144850637-eebce826-5fb0-47df-a219-7b8dff66e430.png)

**Comment by Nohus** [comment] 2021-12-06 13:05
What's the reason for a special `mainLayer`? Now it fells a little hacky to have a special String prefix for it. Can't all unnamed layers just have a random UUID name?

**Comment by peterLaurence** [comment] 2021-12-06 13:08
I've thought of doing this even before this issue. It ensures uniqueness of the main layer, even after primary layer change. Otherwise, I haven't found any reliable way to distinguish old primary tiles from new ones.
And oh yes.. poor naming. I'll make names consistent.

**Comment by Nohus** [comment] 2021-12-06 13:09
Why are "primary tiles" special? Can't all layers be equal with no "primary layer"?

**Comment by peterLaurence** [comment] 2021-12-06 13:10
The primary layer is the only one for which opacity can't be controlled.

**Comment by peterLaurence** [comment] 2021-12-06 13:12
Also the primary layer can't be accidentally removed (the user don't know it's id).

**Comment by Nohus** [comment] 2021-12-06 13:16
> The primary layer is the only one for which opacity can't be controlled.

Why is that limitation necessary? Although definitely less common I could see someone wanting to have a partly transparent first layer, so why limit it?

**Comment by peterLaurence** [comment] 2021-12-06 13:20
> Why is that limitation necessary? Although definitely less common I could see someone wanting to have a partly transparent first layer, so why limit it?

I went for this solution initially, only to realize that it produces bad looking transitions when transitioning between levels. The current level is visible, while part of underneath other levels are visible because the primary layer isn't fully opaque.

**Comment by peterLaurence** [comment] 2021-12-06 13:25
This library has "Map" in it's name, it provides sane defaults for displaying maps.

**Comment by Nohus** [comment] 2021-12-06 13:30
I have a map with multiple style types, and multiple layers in each type. The total will reach over 100 different layers, with the user being able to switch between them or display multiple layers with opacity control. That's why I am wondering how the layers implementation will eventually fit in with my requirements. I don't really think of any of my layer as the "primary".

**Comment by peterLaurence** [comment] 2021-12-06 13:35
Then the primary will be the one underneath all others. I'll try to see if there's a way to make this a library concept (and not requiring the user think in terms of primary layer + other layers).

**Comment by Nohus** [comment] 2021-12-06 13:35
> I'll try to see if there's a way to make this a library concept (and not requiring the user think in terms of primary layer + other layers).

:+1:

**Closed** 2021-12-07 11:16 UTC
